# Generated by Django 5.2.4
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]
    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'password',
                    models.CharField(max_length=128, verbose_name='password'),
                ),
                (
                    'last_login',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='last login'
                    ),
                ),
                (
                    'is_superuser',
                    models.BooleanField(
                        default=False,
                        help_text='Designates that this user has all permissions without explicitly assigning them.',
                        verbose_name='superuser status',
                    ),
                ),
                (
                    'email',
                    models.EmailField(
                        max_length=254, unique=True, verbose_name='Email'
                    ),
                ),
                ('name', models.CharField(max_length=124, verbose_name='Имя')),
                (
                    'surname',
                    models.CharField(max_length=124, verbose_name='Фамилия'),
                ),
                (
                    'avatar',
                    models.ImageField(
                        upload_to='avatars/', verbose_name='Аватар'
                    ),
                ),
                (
                    'phone',
                    models.CharField(
                        max_length=12, unique=True, verbose_name='Телефон'
                    ),
                ),
                (
                    'github_url',
                    models.URLField(blank=True, verbose_name='GitHub'),
                ),
                (
                    'about',
                    models.CharField(
                        blank=True, max_length=256, verbose_name='О себе'
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(default=True, verbose_name='Активен'),
                ),
                (
                    'is_staff',
                    models.BooleanField(
                        default=False, verbose_name='Администратор'
                    ),
                ),
                (
                    'groups',
                    models.ManyToManyField(
                        blank=True,
                        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.group',
                        verbose_name='groups',
                    ),
                ),
                (
                    'user_permissions',
                    models.ManyToManyField(
                        blank=True,
                        help_text='Specific permissions for this user.',
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.permission',
                        verbose_name='user permissions',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=200, verbose_name='Название проекта'
                    ),
                ),
                (
                    'description',
                    models.TextField(blank=True, verbose_name='Описание'),
                ),
                (
                    'created_at',
                    models.DateTimeField(verbose_name='Дата создания'),
                ),
                (
                    'github_url',
                    models.URLField(
                        blank=True, verbose_name='Ссылка на GitHub'
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('open', 'Open'), ('closed', 'Closed')],
                        default='open',
                        max_length=6,
                        verbose_name='Статус',
                    ),
                ),
                (
                    'interested_users',
                    models.ManyToManyField(
                        blank=True,
                        related_name='favorite_projects',
                        to='projects.user',
                        verbose_name='Избран у пользователей',
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='owned_projects',
                        to='projects.user',
                        verbose_name='Автор',
                    ),
                ),
                (
                    'participants',
                    models.ManyToManyField(
                        blank=True,
                        related_name='participated_projects',
                        to='projects.user',
                        verbose_name='Участники',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
    ]
